# Where to store the log file for ZTP Watcher.
logfile: /etc/ztp/logs/ztpwatcher.log

# Location of FreeZTP custom merged-config files, must match path from the 
# `ztp set logging merged-config-to-custom-file` path.
watch_dir: /etc/ztp/logs/merged/

# Use `dns` or provisioning `ip` for SSH connection.
# Use 'parse' to parse FreeZTP merged-config file for an IP address.
ssh_method: ip

# Enter name of file that contains post provisioning configuration, or type
# 'False' (without quotes) if there is none.
post_cfg: /var/git/ztp-watcher/postcfg.txt

# Enter path to push the final configuration to the TFTP server after
# completion, or type 'False' (without quotes).
cfg_push: /complete/

# IP address of TFTP server hosting files and name of image file to copy.
tftpaddr: 172.17.251.251                          
imgfile: c2960x-universalk9-mz.152-4.E8.bin

# Username and password used to authenticate to switches.
username: cisco
password: cisco

# SSH testing variables.
ssh_initialwait: 10
ssh_timeout: 7
ssh_retrywait: 5
ssh_maxattempts: 15